title: console dot log # name of the site
author: Jonathan Staniforth # name of site's author
email: # email of site's author
url: https://consoledotlog.co.uk # root address of the site
description: > # description of the site (multiple lines allowed)
  A collection of developer notes.

permalink: /:slug.html

favicon: "" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag